var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__105knmo._.js")
R.c("server/chunks/ssr/13k~_0lxmmpm._.js")
R.c("server/chunks/ssr/13k~_next_dist_esm_build_templates_app-page_0q~yzd4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j823~v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05ceh.t._.js")
R.c("server/chunks/ssr/Documents_Portfolio_src_app_layout_tsx_0xu3wdf._.js")
R.c("server/chunks/ssr/13k~_next_dist_client_components_0za9_f~._.js")
R.c("server/chunks/ssr/13k~_next_dist_client_components_builtin_forbidden_0_6d-5c.js")
R.c("server/chunks/ssr/13k~_next_dist_client_components_builtin_unauthorized_0cnbz6w.js")
R.c("server/chunks/ssr/13k~_next_dist_client_components_builtin_global-error_08ve45n.js")
R.c("server/chunks/ssr/Documents_Portfolio__next-internal_server_app_page_actions_0tm.ocj.js")
R.m(76140)
module.exports=R.m(76140).exports
