var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__105x1_q._.js")
R.c("server/chunks/ssr/13k~_0lxmmpm._.js")
R.c("server/chunks/ssr/13k~_next_dist_esm_build_templates_app-page_01r874v.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j823~v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__05ceh.t._.js")
R.c("server/chunks/ssr/13k~_next_dist_client_components_builtin_global-error_08ve45n.js")
R.c("server/chunks/ssr/Documents_Portfolio__next-internal_server_app__global-error_page_actions_0by.65g.js")
R.m(63260)
module.exports=R.m(63260).exports
